theme: jekyll-theme-midnight

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - CELL.md
  - CSV.md
  - JSON.md
  - MAIN.md
title: Cellular-Z